on: [pull_request]

jobs:
  checklist_job:
    runs-on: ubuntu-latest
    name: Checklist job
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Checklist
        uses: PokaInc/pr-template-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          template_dir: './'
          mapping: 'feature=feature/'
